apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-disk
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  local:
    path: /data-base/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: local-disk
              operator: In
              values:
                - attached

