apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-disk-pvc
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi