apiVersion: v1
kind: Service
metadata:
  name:  randeerdil-deploymen
  namespace: aks-ingress
spec:
  selector:
    app:  randeerdil
  # ---
  type:  ClusterIP
  ports:
   - name:  http
     port:  80