apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-webapprouting
  namespace: aks-ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: randeerlalanga92@gmail.com
    privateKeySecretRef:
      name: letsencrypt-webapprouting
    solvers:
    - selector: {}
      http01:
        ingress:
          ingressClassName: nginx
