apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-cert
  namespace: portainer
spec:
  secretName: portainer-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'admin.lala-1992.xyz'
