apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rashmika-ingress
  namespace: ingress-test
  #annotations:
  #  nginx.org/rewrites: "serviceName=test4 rewrite=/"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - k8s.lala-1992.xyz
    secretName: website-crt
  rules:
  - host: k8s.lala-1992.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/test1"
        backend:
          service:
            name: test1
            port:
              number: 80
      - pathType: Prefix
        path: "/test2"
        backend:
          service:
            name: test2
            port:
              number: 80
      - pathType: Prefix
        path: "/test3"
        backend:
          service:
            name: test3
            port:
              number: 80
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: test4
            port:
              number: 80
status:
  loadBalancer:
    ingress:
      - ip: 172.26.100.10