apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-com-tls
  issuerRef:
    name: traefik-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - argo.lala-1992.xyz