apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-grpc
  namespace: argocd
spec:
  secretName: argocd-ingress-grpc
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - grpc.argocd.lala-1992.xyz
