apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kasten-io-k8s
  namespace: kasten-io
spec:
  secretName: kasten-io-k8s
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'kasten.lala-1992.xyz'