apiVersion: v1
kind: Pod
metadata:
  name: nginx-nfs-dynamic-pod
spec:
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: my-nfs
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "nginx-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs-storage