apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleport
  namespace: teleport-cluster
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: teleport
  template:
    metadata:
      labels:
        app: teleport
    spec:
      containers:
        - name: teleport
          image: public.ecr.aws/gravitational/teleport-distroless:13
          volumeMounts:
            - name: config-volume
              mountPath: /etc/teleport
            - name: data-volume
              mountPath: /var/lib/teleport
          # Add any additional container configuration here
      volumes:
        - name: config-volume
          configMap:
            name: teleport-config  # Name of the ConfigMap containing Teleport configuration
        - name: data-volume
          persistentVolumeClaim:
            claimName: teleport-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: teleport-service
  namespace: teleport-cluster
spec:
  selector:
    app: teleport
  ports:
    - name: http
      port: 3080  # Adjust the port as needed
      targetPort: 3080  # Adjust the target port if necessary
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport-ingress
  namespace: teleport-cluster
  annotations:
    traefik.enable: "true"
    traefik.http.services.teleport.loadbalancer.server.port: "3080"
    traefik.http.services.teleport.loadbalancer.server.scheme: "https"
    traefik.http.routers.teleport-http.entrypoints: "web"
    traefik.http.routers.teleport-http.rule: "HostRegexp(`traefik.lala-1992.xyz`, `{subhost:[a-z]+}.traefik.lala-1992.xyz`)"
    traefik.http.routers.teleport-https.entrypoints: "websecure"
    traefik.http.routers.teleport-https.rule: "HostRegexp(`traefik.lala-1992.xyz`, `{subhost:[a-z]+}.traefik.lala-1992.xyz`)"
    traefik.http.routers.teleport-https.tls: "true"
    traefik.http.routers.teleport-https.tls.certresolver: "cloudflare"
    #traefik.ingress.kubernetes.io/router.tls.domains[0].main: "lala-1992.xyz"
    #traefik.ingress.kubernetes.io/router.tls.domains[0].sans: "traefik.lala-1992.xyz"
  #  traefik.http.routers.teleport-https.tls.domains[0].main: "traefik.lala-1992.xyz"  # Changed the domain name
  #  traefik.http.routers.teleport-https.tls.domains[0].sans: "*traefik.lala-1992.xyz"  # Changed the domain name
spec:
  ingressClassName: traefik
  rules:
    - host: traefik.lala-1992.xyz  # Replace with your actual server URL
      http:
        paths:
          - pathType: Prefix
            path: /  # Adjust the path as needed
            backend:
              service:
                name: teleport-service
                port:
                  number: 3080  # Adjust the port if necessary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-config-pvc
  namespace: teleport-cluster
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce  # Adjust the access mode as needed
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-data-pvc
  namespace: teleport-cluster
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce  # Adjust the access mode as needed
  resources:
    requests:
      storage: 10Gi  # Adjust the storage size as needed
