apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-k8s
  namespace: nginx-test
spec:
  secretName: nginx-test-k8s
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'k8s.lala-1992.xyz'